module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './stories/**/*.{js,ts,jsx,tsx,mdx}',
    './.storybook/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'var(--font-noto-sans-kr)',
          'Noto Sans KR',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
      },
      colors: {
        primary: {
          900: 'var(--color-primary-900)',
          800: 'var(--color-primary-800)',
          700: 'var(--color-primary-700)',
          600: 'var(--color-primary-600)',
          500: 'var(--color-primary-500)',
          400: 'var(--color-primary-400)',
          300: 'var(--color-primary-300)',
          200: 'var(--color-primary-200)',
          100: 'var(--color-primary-100)',
          50: 'var(--color-primary-50)',
        },
        success: {
          900: 'var(--color-success-900)',
          800: 'var(--color-success-800)',
          700: 'var(--color-success-700)',
          600: 'var(--color-success-600)',
          500: 'var(--color-success-500)',
          400: 'var(--color-success-400)',
          300: 'var(--color-success-300)',
          200: 'var(--color-success-200)',
          100: 'var(--color-success-100)',
          50: 'var(--color-success-50)',
        },
        danger: {
          900: 'var(--color-danger-900)',
          800: 'var(--color-danger-800)',
          700: 'var(--color-danger-700)',
          600: 'var(--color-danger-600)',
          500: 'var(--color-danger-500)',
          400: 'var(--color-danger-400)',
          300: 'var(--color-danger-300)',
          200: 'var(--color-danger-200)',
          100: 'var(--color-danger-100)',
          50: 'var(--color-danger-50)',
        },
        info: {
          900: 'var(--color-info-900)',
          800: 'var(--color-info-800)',
          700: 'var(--color-info-700)',
          600: 'var(--color-info-600)',
          500: 'var(--color-info-500)',
          400: 'var(--color-info-400)',
          300: 'var(--color-info-300)',
          200: 'var(--color-info-200)',
          100: 'var(--color-info-100)',
          50: 'var(--color-info-50)',
        },
        neutral: {
          100: 'var(--color-neutral-100)',
          90: 'var(--color-neutral-90, #444444)',
          80: 'var(--color-neutral-80, #444444)',
          70: 'var(--color-neutral-70, #656565)',
          60: 'var(--color-neutral-60)',
          40: 'var(--color-neutral-40)',
          30: 'var(--color-neutral-30)',
          20: 'var(--color-neutral-20)',
          10: 'var(--color-neutral-10, #fdfdfd)',
          0: 'var(--color-neutral-0)',
        },
      },
      fontSize: {
        h1: ['var(--font-size-h1)', { lineHeight: 'var(--line-height-h1)' }],
        h2: ['var(--font-size-h2)', { lineHeight: 'var(--line-height-h2)' }],
        h3: ['var(--font-size-h3)', { lineHeight: 'var(--line-height-h3)' }],
        h4: ['var(--font-size-h4)', { lineHeight: 'var(--line-height-h4)' }],
        h5: ['var(--font-size-h5)', { lineHeight: 'var(--line-height-h5)' }],
        h6: ['var(--font-size-h6)', { lineHeight: 'var(--line-height-h6)' }],
        'extra-large': [
          'var(--font-size-extra-large)',
          { lineHeight: 'var(--line-height-extra-large)' },
        ],
        large: ['var(--font-size-large)', { lineHeight: 'var(--line-height-large)' }],
        medium: ['var(--font-size-medium)', { lineHeight: 'var(--line-height-medium)' }],
        small: ['var(--font-size-small)', { lineHeight: 'var(--line-height-small)' }],
        tiny: ['var(--font-size-tiny)', { lineHeight: 'var(--line-height-tiny)' }],
      },
      fontWeight: {
        thin: 'var(--font-weight-thin)',
        light: 'var(--font-weight-light)',
        regular: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        bold: 'var(--font-weight-bold)',
        'extra-bold': 'var(--font-weight-extra-bold)',
      },
      screens: {
        mobile: '320px',
        tablet: '768px',
        desktop: '1024px',
        wide: '1280px',
        'ultra-wide': '1920px',
      },
    },
  },
  plugins: [],
};
